### PR TITLE
refactor(types)!: Made naming and interface usage more consistent (closes #119)

### LINKED ISSUE #119: Check Library interfaces
I think the library interfaces right now mix information that is received from the H5P Hub and that is taken from library.json. Sadly, the formats are not exactly the same. The format that is used in library.json is already specified in library-schema.json and should be the one that is used in ILibraryJson. The format we get from the hub is the one in the Library class.

We should also use more telling names like ILibraryJson, HubLibrary and a clearer one for ILibraryData (can't think of one right now).

### PR DESCRIPTION
**Pull request by sr258**
In this PR, the somewhat inconsistent usage of library interfaces and classes has been made consistent:

- Every library interface in types.ts now has a clear and understandable name to differentiate them. There also is a clear inheritance hierarchy between them.
- The library interfaces in types.ts no longer extend the Library class.
- The LibraryManager and FileLibraryStorage classes use the minimal interfaces needed for their functionality. Before, they always used the full Library class, even though they only require a machine name, major version and minor version.

Sorry that the PR changes so much, but there are no smaller steps possible to tackle the issues of inconsistency in this area.

The PR is not fully finished yet. I have to re-check everything, but it's too late for this today.

### CODE REVIEW

**Comment by JPSchellenberg** [comment]
That's a great and long overdue PR. I wanted to refactor the types for a long time but postponed it every time. :) 
After we refactored this, how comfortable are you with the API? Do you think we could release it as v1.0.0 after this PR is merged?

**Comment by sr258** [comment]
We're approaching API 1.0, but I don't think we're there yet:
- The storage interfaces don't have all necessary CRUD operations, I think. (e.g. deleting is missing #146 )
- We still have to decide on a consistent way of reporting back errors and success (see #83)
- I think we should also decide where to check permissions (#112). Currently the storage objects have method signatures that imply that the storage provider has to / can check permissions. 
- #44 also has to be settled: Currently all components that emit messages to the user have a dependency on the translation service. It might be better to remove the dependency and simply emit H5pError objects. The actual localization is then done in the presentation layer (H5pEditor). (It's possible that this won't affect the API)

Maybe a phone call is easier on this than to do it all by typing?

**Comment by sr258** [comment]
The PR is ready to be reviewed, I think. I haven't yet split the types.ts file into two to not make the PR even bigger and more confusing.

**Review by JPSchellenberg — APPROVED** [review]

**Comment by JPSchellenberg** [comment]
> Maybe a phone call is easier on this than to do it all by typing?


Yeah, I think this is a good idea. I'll contact you in Slack

**Pull request merged**
