### PR TITLE
feat(html export): added html exporter

### PR DESCRIPTION
**Pull request by sr258**
The export is not finished yet (but it works) and it might be better to put it into its own package, as there are some heavy dependencies in it (postcss and uglify-js).

### CODE REVIEW

**Comment by sr258** [comment]
The export itself works now and the automatic tests pass for all hub content types. I haven't tested all content types manually yet, however.

I've put the HtmlExporter specific dependencies (postcss, postcss-clean, postcss-url, postcss-safe-parser, uglify-js) in the dev dependencies to avoid having them in projects that don't need them. I'm not entirely sure if the package will transpile in typescript if these dependencies are not installed, though. @JPSchellenberg Any guess about this?

**Comment by JPSchellenberg** [comment]
The package does not compile when these dependencies are not installed. Further more I think it will not work during runtime, when these dependencies are not installed. I would suggest to put them into the depedencies and fix that issue later when we are divinding the package into multiple packages.

**Comment by sr258** [comment]
@JPSchellenberg fixed that. It should be ready to be merged.

**Review by JPSchellenberg — APPROVED** [review]
This is a really great feature!

**Pull request merged**
