### PR TITLE
Add puppeteer test (headless chrome test)

### PR DESCRIPTION
**Pull request by JPSchellenberg**
Hey,

today I found out, that the depedency-order seems to be faulty. This seems to be the same problem like the one with the async-libraryLoader in the H5P-Nodejs-library. I already opened an issue (#47) and this PR adds a test with puppeteer to see if the editor throws any error when accessing certain pages.

The problem is, that the test needs the libraries to be installed. Right now it loads the 'Library Install' page and then does nothing, so in order to get the test running, we need to implement the installLibrary-function (#12). I think @sr258 is working on the library-validator in order to install libraries. We can either help @sr258 with the validator or we implement the installLibrary without validation and add the validtor later on.
@rtens @sr258 How do you want to proceed?

### CODE REVIEW

**Comment by rtens** [comment]
@sr258 seems to be making great [progress with the validation](#50), but I don't see a reason why not to go ahead and implement installLibrary without validation first. 

@sr258 are you working on validation only or also on installation?

**Comment by sr258** [comment]
My next step would have been to work on the installation process of libraries. The validator will be finished soon, so it would make sense to continue there. I‘m on holiday at the moment, so I will have some time to work on it. 

I thought of extending FileLibraryManager which is currently a mock-up by separating it into a generic LibraryManager class and a FileLibraryStorage class that does the actual storage. That way storage can also be in a Redis Cache or on a S3 by exchanging FileLibraryStorage with RedisLibraryStorage etc.

**Comment by rtens** [comment]
Nice. Sounds good to me =)

**Comment by rtens** [comment]
@JPSchellenberg Do you still wanna merge this? If so, then go ahead. Otherwise let's close this PR.

**Comment by JPSchellenberg** [comment]
@rtens I am still working on it as the tests do not pass, but I plan on fixing that and merging this today as it depended on the installLibrary-method.

**Comment by sr258** [comment]
How about using Jest for the Puppeteer tests as well? It seems to work fine and this would allow better error reporting if there are more Puppeteer tests in the future: https://jestjs.io/docs/en/puppeteer

**Comment by JPSchellenberg** [comment]
I will close this PR as it is easier to make a new branch from master and add the tests there.

**Pull request closed without merging**
