### PR TITLE
fix(h5p-server): now exports UrlGenerator

### PR DESCRIPTION
**Pull request by sr258**

### CODE REVIEW

**Comment by 0xMurage** [comment]
I was wondering why my local package I installed yesterday didn't have this. Can the team find a way to ensure the respective affected package version increment accordingly after fixing/adding a feature.

@sr258 thank you for this.

**Comment by sr258** [comment]
It's not in the release branch yet. did you clone the repo or install it via NPM?

**Comment by 0xMurage** [comment]
installed through NPM

**Comment by sr258** [comment]
It will be included in the future release 7.2.0 once https://github.com/Lumieducation/H5P-Nodejs-library/pull/1133 has been merged. (soon) In the meantime you can do submodule imports with `import UrlGenerator from '@h5p-server/build/src/...`.

**Comment by 0xMurage** [comment]
thank you. I hadn't noticed the release branch is used to publish to the npm upstream.

**Comment by sr258** [comment]
I've triggered the release.

**Pull request merged**
