### PR TITLE
fix(package upload): content of uploaded packages is now not permanently stored in the system

### PR DESCRIPTION
**Pull request by sr258**
- [X] change signatures of PackageImporter to return metadata and parameters instead of contentId
- [X] implement logic to copy content files to temporary storage

### CODE REVIEW

**Comment by sr258** [comment]
Turns out the POST request to the 'filter' Ajax endpoint invokes some method of H5PContentValidator in the PHP implementation, which is a 1340 lines long class doing lots of stuff...

I don't want to implement this right away, but have a closer look at what this is doing. At the moment, I simply don't "filter" the parameters but return them. Uploading packages works fine, though, but maybe things aren't as safe as we want them to be.

**Comment by sr258** [comment]
Closes #278

**Comment by sr258** [comment]
Rerunning the tests worked... weird.

**Review by JPSchellenberg — APPROVED** [review]

**Pull request merged**
